nginx-ssl-proxy:
  image: danieldent/nginx-ssl-proxy
  restart: always
  environment:
    UPSTREAM: 127.0.0.1:6999
    SERVERNAME: localhost
    EXTRANAMES: 127.0.0.1
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - "/etc/letsencrypt"